site_name: Lagoobernetes

pages:
- Home: index.md
- Using Lagoobernetes:
  - Overview: using_lagoobernetes/index.md
  - Local Development Environments: using_lagoobernetes/local_development_environments.md
  - Setup a new Project in Lagoobernetes: using_lagoobernetes/setup_project.md
  - Configure Webhooks: using_lagoobernetes/configure_webhooks.md
  - First Deployment: using_lagoobernetes/first_deployment.md
  - Drupal:
    - Getting Drupal ready to run on Lagoobernetes: using_lagoobernetes/drupal/lagoobernetesize.md
    - First Deployment: using_lagoobernetes/drupal/first_deployment.md
    - Drush 9: using_lagoobernetes/drupal/drush9.md
    - Subfolders: using_lagoobernetes/drupal/subfolders.md
    - Services:
      - MariaDB: using_lagoobernetes/drupal/services/mariadb.md
      - Solr: using_lagoobernetes/drupal/services/solr.md
      - Varnish: using_lagoobernetes/drupal/services/varnish.md
      - Redis: using_lagoobernetes/drupal/services/redis.md
  - .lagoobernetes.yml: using_lagoobernetes/lagoobernetes_yml.md
  - docker-compose.yml: using_lagoobernetes/docker-compose_yml.md
  - Service Types: using_lagoobernetes/service_types.md
  - Build & Deployment Process: using_lagoobernetes/build_deploy_process.md
  - Environment Types: using_lagoobernetes/environment_types.md
  - Environment Variables: using_lagoobernetes/environment_variables.md
  - Base Images: using_lagoobernetes/base_images.md
  - Workflows: using_lagoobernetes/workflows.md
  - Backups: using_lagoobernetes/backups.md
  - Going Live: using_lagoobernetes/golive.md
  - Logs:
     - Logging: using_lagoobernetes/logging/logging.md
     - Kibana Examples: using_lagoobernetes/logging/kibana_examples.md
  - Remote Shell: using_lagoobernetes/remote_shell.md
  - GraphQL API: using_lagoobernetes/graphql_api.md
  - Node.js:
    - Graceful Shutdown: using_lagoobernetes/nodejs/graceful_shutdown.md
  - Migrations:
    - From amazee.io: using_lagoobernetes/migrations/amazeeio.md
- Administration:
  - Installing Lagoobernetes: administering_lagoobernetes/install.md
  - OpenShift Requirements: administering_lagoobernetes/openshift_requirements.md
  - GraphQL API: administering_lagoobernetes/graphql_api.md
  - Role Based Access Control: administering_lagoobernetes/rbac.md
  - SSL Ciphers: administering_lagoobernetes/ssl_ciphers.md
  - Harbor:
    - Using Harbor: using_lagoobernetes/harbor/using_harbor.md
    - Security Scanning: using_lagoobernetes/harbor/security_scanning.md
    - Harbor Settings: using_lagoobernetes/harbor/harbor_settings.md
      - harborclair: using_lagoobernetes/harbor/harbor-container-settings/harborclair.md
      - harborclairadapter: using_lagoobernetes/harbor/harbor-container-settings/harborclairadapter.md
      - harborregistry: using_lagoobernetes/harbor/harbor-container-settings/harborregistry.md
      - harborregistryctl: using_lagoobernetes/harbor/harbor-container-settings/harborregistryctl.md
      - harbor-core: using_lagoobernetes/harbor/harbor-container-settings/harbor-core.md
      - harbor-database: using_lagoobernetes/harbor/harbor-container-settings/harbor-database.md
      - harbor-jobservice: using_lagoobernetes/harbor/harbor-container-settings/harbor-jobservice.md
- Docker Images:
  - Elasticsearch: using_lagoobernetes/docker_images/elasticsearch.md
  - MariaDB Drupal: using_lagoobernetes/docker_images/mariadb-drupal.md
  - MariaDB: using_lagoobernetes/docker_images/mariadb.md
  - MongoDB: using_lagoobernetes/docker_images/mongo.md
  - Nginx Drupal: using_lagoobernetes/docker_images/nginx-drupal.md
  - Nginx: using_lagoobernetes/docker_images/nginx.md
  - PHP CLI Drupal: using_lagoobernetes/docker_images/php-cli-drupal.md
  - PHP CLI: using_lagoobernetes/docker_images/php-cli.md
  - PHP-FPM: using_lagoobernetes/docker_images/php-fpm.md
  - Postgres: using_lagoobernetes/docker_images/postgres.md
  - RabbitMQ: using_lagoobernetes/docker_images/rabbitmq.md
  - Redis Persistent: using_lagoobernetes/docker_images/redis-persistent.md
  - Redis: using_lagoobernetes/docker_images/redis.md
  - Solr Drupal: using_lagoobernetes/docker_images/solr-drupal.md
  - Solr: using_lagoobernetes/docker_images/solr.md
  - Varnish Drupal: using_lagoobernetes/docker_images/varnish-drupal.md
  - Varnish: using_lagoobernetes/docker_images/varnish.md
- Development:
  - Developing Lagoobernetes: developing_lagoobernetes/index.md
  - Tests: developing_lagoobernetes/tests.md
  - Contributing: developing_lagoobernetes/contributing.md
  - API Debugging: developing_lagoobernetes/api-debugging.md
  - Code Of Conduct: developing_lagoobernetes/code_of_conduct.md
theme: readthedocs

markdown_extensions:
  - toc:
      permalink: true
      baselevel: 1
  - admonition

extra_css: [_static/theme_overrides.css]
