#!/bin/sh

# Make sure that new files generated by Docker have group write permission
source /lagoobernetes/entrypoints/00-umask.sh

# Loading environment variables from .env and friends
source /lagoobernetes/entrypoints/50-dotenv.sh

# Generate some additional enviornment variables
source /lagoobernetes/entrypoints/55-generate-env.sh

# a nicer prompt
if [ "$PS1" ]; then
  NORMAL="\[\e[0m\]"
  RED="\[\e[1;31m\]"
  GREEN="\[\e[0;32m\]"
  YELLOW="\[\e[1;33m\]"
  BLUE="\[\e[1;34m\]"
  WHITE="\[\e[1;37m\]"
  PS1="${YELLOW}\w${NORMAL}$ "
  if [ "$LAGOOBERNETES" ]; then
    PS1="${GREEN}$LAGOOBERNETES${NORMAL}:$PS1"
  fi
  if [ "$LAGOOBERNETES_GIT_BRANCH" ]; then
    # production environments get a red color
    if [ "$LAGOOBERNETES_ENVIRONMENT_TYPE" == "production" ]; then
      PS1="${RED}$LAGOOBERNETES_GIT_BRANCH${NORMAL}@$PS1"
    else
      PS1="${BLUE}$LAGOOBERNETES_GIT_BRANCH${NORMAL}@$PS1"
    fi
  fi
  if [ "$LAGOOBERNETES_PROJECT" ]; then
    PS1="[${WHITE}$LAGOOBERNETES_PROJECT${NORMAL}]$PS1"
  fi
fi

# Helpers
alias ll="ls -l"
