apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: lagoobernetes-openshift-template-logstash
parameters:
  - name: SERVICE_NAME
    description: Name of this service
    required: true
  - name: SAFE_BRANCH
    description: Which branch this belongs to, special chars replaced with dashes
    required: true
  - name: SAFE_PROJECT
    description: Which project this belongs to, special chars replaced with dashes
    required: true
  - name: BRANCH
    description: Which branch this belongs to, original value
    required: true
  - name: PROJECT
    description: Which project this belongs to, original value
    required: true
  - name: LAGOOBERNETES_GIT_SHA
    description: git hash sha of the current deployment
    required: true
  - name: SERVICE_ROUTER_URL
    description: URL of the Router for this service
    value: ""
  - name: OPENSHIFT_PROJECT
    description: Name of the Project that this service is in
    required: true
  - name: REGISTRY
    description: Registry where Images are pushed to
    required: true
  - name: DEPLOYMENT_STRATEGY
    description: Strategy of Deploymentconfig
    value: "Rolling"
  - name: SERVICE_IMAGE
    description: Pullable image of service
    required: true
  - name: CRONJOBS
    description: Oneliner of Cronjobs
    value: ""
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      branch: ${SAFE_BRANCH}
      project: ${SAFE_PROJECT}
    name: ${SERVICE_NAME}
  spec:
    replicas: 3
    selector:
      service: ${SERVICE_NAME}
    strategy:
      type: ${DEPLOYMENT_STRATEGY}
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: ${SERVICE_NAME}
          branch: ${SAFE_BRANCH}
          project: ${SAFE_PROJECT}
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: service
                      operator: In
                      values:
                        - ${SERVICE_NAME}
                topologyKey: kubernetes.io/hostname
        containers:
        - image: ${SERVICE_IMAGE}
          name: ${SERVICE_NAME}
          ports:
          - containerPort: 9600
            protocol: TCP
          readinessProbe:
            httpGet:
              port: 9600
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              port: 9600
            initialDelaySeconds: 120
          envFrom:
          - configMapRef:
              name: lagoobernetes-env
          env:
            - name: CRONJOBS
              value: ${CRONJOBS}
            - name: SERVICE_NAME
              value: ${SERVICE_NAME}
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  key: RABBITMQ_USERNAME
                  name: rabbitmq-username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: RABBITMQ_PASSWORD
                  name: rabbitmq-password
            - name: LOGSDB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: LOGSDB_ADMIN_PASSWORD
                  name: logs-db-admin-password
            - name: XPACK_MANAGEMENT_ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: LOGSDB_ADMIN_PASSWORD
                  name: logs-db-admin-password
            - name: XPACK_MONITORING_ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: LOGSDB_ADMIN_PASSWORD
                  name: logs-db-admin-password
            - name: LOGSTASH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: logstash-username
                  key: LOGSTASH_USERNAME
            - name: LOGSTASH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logstash-password
                  key: LOGSTASH_PASSWORD
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      service: ${SERVICE_NAME}
      branch: ${SAFE_BRANCH}
      project: ${SAFE_PROJECT}
    name: ${SERVICE_NAME}
  spec:
    ports:
    - name: logstash-mgmt
      port: 9600
      protocol: TCP
      targetPort: 9600
    - name: udp-input-module
      port: 5140
      protocol: UDP
      targetPort: 5140
    - name: tcp-input-module
      port: 28777
      protocol: TCP
      targetPort: 28777
    selector:
      service: ${SERVICE_NAME}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: ${SERVICE_NAME}
      branch: ${SAFE_BRANCH}
      project: ${SAFE_PROJECT}
    name: ${SERVICE_NAME}-lumberjack
  spec:
    ports:
      - name: lumberjack-input-module
        port: 5044
        protocol: TCP
        targetPort: 5044
    selector:
      service: ${SERVICE_NAME}
    type: NodePort
- apiVersion: v1
  kind: Service
  metadata:
    name: router-logs
  spec:
    externalName: ${SERVICE_NAME}.${OPENSHIFT_PROJECT}.svc.cluster.local
    sessionAffinity: None
    type: ExternalName
- apiVersion: v1
  kind: Service
  metadata:
    name: application-logs
  spec:
    externalName: ${SERVICE_NAME}.${OPENSHIFT_PROJECT}.svc.cluster.local
    sessionAffinity: None
    type: ExternalName
