apiVersion: v1
kind: RoleBinding
metadata:
  name: shared-resource-viewers
  namespace: lagoobernetes
groupNames:
- system:authenticated
roleRef:
  name: shared-resource-viewer
  namespace: lagoobernetes
subjects:
- kind: SystemGroup
  name: system:authenticated
userNames: null