apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cli.fullname" . }}
  labels:
    {{- include "cli.labels" . | nindent 4 }}
  annotations:
    {{- include "cli.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cli.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cli.labels" . | nindent 8 }}
      annotations:
        {{- include "cli.annotations" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      priorityClassName: {{ include "cli.lagoobernetesPriority" . }}
      enableServiceLinks: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: lagoobernetes-sshkey
          secret:
            defaultMode: 420
            secretName: lagoobernetes-sshkey
      containers:
        - image: {{ .Values.image | quote }}
          name: {{ include "cli.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: CRONJOBS
              value: {{ .Values.inPodCronjobs | quote }}
            ## LAGOOBERNETES_GIT_SHA is injected directly and not loaded via `lagoobernetes-env` config
            ## This will cause the pod to redeploy on every deployment, even the files have not changed
            - name: LAGOOBERNETES_GIT_SHA
              value: {{ .Values.gitSha | quote }}
            - name: SERVICE_NAME
              value: {{ .Release.Name | quote }}
          envFrom:
            - configMapRef:
                name: lagoobernetes-env
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/run/secrets/lagoobernetes/sshkey/
              name: lagoobernetes-sshkey
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
