version: '2'
services:
  testing:
    build:
      context: ../..
      dockerfile: services/drush-alias/testing/Dockerfile
    environment:
      # Make sure to run lagoobernetes with properly configured hiera repo
      # otherwise the script will not find any data for the project
      - LAGOOBERNETES_PROJECT=ci-drupal
      - LAGOOBERNETES_OVERRIDE_SSH=172.17.0.1:2020
      - LAGOOBERNETES_OVERRIDE_API=http://api:3000
      - LAGOOBERNETES_DEBUG=true
      #- LAGOOBERNETES_IGNORE_DRUSHCACHE=true
    volumes:
      - './web/aliases.drushrc.php.stub:/etc/drush/aliases.drushrc.php.stub'
    networks:
      - lagoobernetes_default
networks:
  lagoobernetes_default:
    external: true
