{{- if .Values.dockerHost.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lagoobernetes-remote.dockerHost.serviceAccountName" . }}
  labels:
{{ include "lagoobernetes-remote.dockerHost.labels" . | nindent 4 }}
{{- end -}}
