apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lagoobernetes-remote.kubernetesbuilddeploy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "lagoobernetes-remote.labels" . | nindent 4 }}