apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: lagoobernetes-remote-openshift-template-logs-collector
parameters:
  - name: SERVICE_NAME
    description: Name of this service
    required: true
  - name: SAFE_BRANCH
    description: Which branch this belongs to, special chars replaced with dashes
    required: true
  - name: SAFE_PROJECT
    description: Which project this belongs to, special chars replaced with dashes
    required: true
  - name: BRANCH
    description: Which branch this belongs to, original value
    required: true
  - name: PROJECT
    description: Which project this belongs to, original value
    required: true
  - name: LAGOOBERNETES_GIT_SHA
    description: git hash sha of the current deployment
    required: true
  - name: SERVICE_ROUTER_URL
    description: URL of the Router for this service
    value: ""
  - name: OPENSHIFT_PROJECT
    description: Name of the Project that this service is in
    required: true
  - name: REGISTRY
    description: Registry where Images are pushed to
    required: true
  - name: DEPLOYMENT_STRATEGY
    description: Strategy of Deploymentconfig
    value: "Rolling"
  - name: SERVICE_IMAGE
    description: Pullable image of service
    required: true
objects:
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    labels:
      service: ${SERVICE_NAME}
      branch: ${SAFE_BRANCH}
      project: ${SAFE_PROJECT}
    name: ${SERVICE_NAME}
  spec:
    selector:
      matchLabels:
        service: ${SERVICE_NAME}
        branch: ${SAFE_BRANCH}
        project: ${SAFE_PROJECT}
    template:
      metadata:
        labels:
          service: ${SERVICE_NAME}
          branch: ${SAFE_BRANCH}
          project: ${SAFE_PROJECT}
        name: ${SERVICE_NAME}
      spec:
        containers:
        - env:
          - name: K8S_HOST_URL
            value: https://kubernetes.default.svc.cluster.local
          - name: ES_HOST
            value: none
          - name: ES_PORT
            value: "9200"
          - name: ES_CLIENT_CERT
            value: /etc/fluent/keys/cert
          - name: ES_CLIENT_KEY
            value: /etc/fluent/keys/key
          - name: ES_CA
            value: /etc/fluent/keys/ca
          - name: OPS_HOST
            value: none
          - name: OPS_PORT
            value: "9200"
          - name: OPS_CLIENT_CERT
            value: /etc/fluent/keys/cert
          - name: OPS_CLIENT_KEY
            value: /etc/fluent/keys/key
          - name: OPS_CA
            value: /etc/fluent/keys/ca
          - name: ES_COPY
            value: "false"
          - name: JOURNAL_SOURCE
          - name: JOURNAL_READ_FROM_HEAD
          - name: BUFFER_QUEUE_LIMIT
            value: "32"
          - name: BUFFER_SIZE_LIMIT
            value: 8m
          - name: FLUENTD_CPU_LIMIT
            valueFrom:
              resourceFieldRef:
                containerName: ${SERVICE_NAME}
                divisor: "0"
                resource: limits.cpu
          - name: FLUENTD_MEMORY_LIMIT
            valueFrom:
              resourceFieldRef:
                containerName: ${SERVICE_NAME}
                divisor: "0"
                resource: limits.memory
          - name: FILE_BUFFER_LIMIT
            value: 256Mi
          - name: LOGS_FORWARDER_SHARED_KEY
            value: secret
          envFrom:
          - configMapRef:
              name: lagoobernetes-env
          image: registry.access.redhat.com/openshift3/logging-fluentd:v3.6
          name: ${SERVICE_NAME}
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /run/log/journal
            name: runlogjournal
          - mountPath: /var/log
            name: varlog
          - mountPath: /var/lib/docker/containers
            name: varlibdockercontainers
            readOnly: true
          - mountPath: /etc/fluent/configs.d/user
            name: config
            readOnly: true
          - mountPath: /etc/docker-hostname
            name: dockerhostname
            readOnly: true
          - mountPath: /etc/localtime
            name: localtime
            readOnly: true
          - mountPath: /etc/sysconfig/docker
            name: dockercfg
            readOnly: true
          - mountPath: /etc/docker
            name: dockerdaemoncfg
            readOnly: true
          - mountPath: /var/lib/fluentd
            name: filebufferstorage
          - mountPath: /fluentd/ssl/
            name: ca-cert
        restartPolicy: Always
        serviceAccount: logs-collector
        serviceAccountName: logs-collector
        tolerations:
          - effect: NoSchedule
            key: autoscaled
            operator: Equal
            value: 'true'
          - effect: NoSchedule
            key: appuio.ch/autoscaled
            operator: Equal
            value: 'true'
          - effect: NoSchedule
            key: lagoobernetes/build
            operator: Exists
        volumes:
        - hostPath:
            path: /run/log/journal
          name: runlogjournal
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers
        - configMap:
            defaultMode: 420
            name: ${SERVICE_NAME}-config
          name: config
        - hostPath:
            path: /etc/hostname
          name: dockerhostname
        - hostPath:
            path: /etc/localtime
          name: localtime
        - hostPath:
            path: /etc/sysconfig/docker
          name: dockercfg
        - hostPath:
            path: /etc/docker
          name: dockerdaemoncfg
        - hostPath:
            path: /var/lib/fluentd
          name: filebufferstorage
        - configMap:
            items:
            - key: LOGS_FORWARDER_CA_CERT
              path: ca_cert.pem
            name: ${SERVICE_NAME}-config
          name: ca-cert
    templateGeneration: 1
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 1
      type: RollingUpdate
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${SERVICE_NAME}-config
  data:
    fluent.conf: |
      # This file is the fluentd configuration entrypoint. Edit with care.

      #@include configs.d/openshift/system.conf

      <system>
        log_level info
      </system>

      ## sources
      ## ordered so that syslog always runs last...
      #@include configs.d/dynamic/input-docker-*.conf

      <source>
        @type tail
        @label @INGRESS
        path "/var/log/containers/*.log"
        pos_file "/var/log/es-containers.log.pos"
        time_format %Y-%m-%dT%H:%M:%S.%N%Z
        tag kubernetes.*
        format json
        keep_time_key true
        read_from_head "true"
        exclude_path ["/var/log/containers/logs-collector*", "/var/log/containers/logs-forwarder*"]
      </source>

      @include configs.d/dynamic/input-syslog-*.conf
      @include configs.d/openshift/input-post-*.conf
      ##

      <label @INGRESS>
      ## filters
        @include configs.d/openshift/filter-pre-*.conf
        @include configs.d/openshift/filter-retag-journal.conf
        @include configs.d/openshift/filter-k8s-meta.conf
        @include configs.d/openshift/filter-kibana-transform.conf
        @include configs.d/openshift/filter-k8s-flatten-hash.conf
        @include configs.d/openshift/filter-k8s-record-transform.conf
        @include configs.d/openshift/filter-syslog-record-transform.conf
        @include configs.d/openshift/filter-viaq-data-model.conf
        @include configs.d/openshift/filter-post-*.conf

        <match **>
          @type copy
          @include configs.d/user/secure-forward.conf
        </match>

      </label>
    secure-forward.conf: |
      <store>
        @type secure_forward
        self_hostname "#{ENV['HOSTNAME']}"
        secure true
        shared_key "#{ENV['LOGS_FORWARDER_SHARED_KEY']}"
        ca_cert_path "/fluentd/ssl/ca_cert.pem"
        <server>
          host logs-forwarder
          port 24284
        </server>

        flush_interval 1s
      </store>
    LOGS_FORWARDER_CA_CERT: |-
      -----BEGIN CERTIFICATE-----
      MIIDIDCCAggCAQEwDQYJKoZIhvcNAQELBQAwTTELMAkGA1UEBhMCVVMxCzAJBgNV
      BAgMAkNBMRYwFAYDVQQHDA1Nb3VudGFpbiBWaWV3MRkwFwYDVQQDDBBTZWN1cmVG
      b3J3YXJkIENBMB4XDTcwMDEwMTAwMDAwMFoXDTIzMDUzMTE4MTQyOVowTTELMAkG
      A1UEBhMCVVMxCzAJBgNVBAgMAkNBMRYwFAYDVQQHDA1Nb3VudGFpbiBWaWV3MRkw
      FwYDVQQDDBBTZWN1cmVGb3J3YXJkIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
      MIIBCgKCAQEA60S/3/jRlMoNEwnCPsa++7vuQ5wScEPkCikTmisH400LUHG+yl4L
      pxp3yYJqSfUougyDE3D9Tm/1toexrZJS0uLotNxdsbwcJfJaAdO5T5auhWkxzwQp
      RCALXgOI+JdIIkj6qSuX3HJIqKOnWRzr8H/0tBM0z2sVT86VG8f4VPgMhfKfN3dg
      XiZjM70BZfw5lq3QIbyyP7zjdN8h0rgleC3VpyKl9pU3T0aXsSFfREqst9M6kvbY
      ls0kciEdAaN/KZxb11gAZpBFe4pDYTR77ux3QSuZFpqWx0y2ZKbD8OYKDows+khB
      BQc1hIhmQoGc9Y9q37x7KW9q0RShnitulQIDAQABoxAwDjAMBgNVHRMEBTADAQH/
      MA0GCSqGSIb3DQEBCwUAA4IBAQA+K6qyduJPWAuBa+o0IzSvgHvnoEw6CsiZ7V9G
      qKlUNkT7nf8lrPAA5mVC+B3vt/dM91+X3zDTzY/DUHK+tRyNs3S0JvMTym4JuZ/F
      mUOpRzna+75//8YwUVto9CnE/0Ae+j+6A0WUzxOQ0SD5Z77h1gQHOw9OKnZoyGJy
      T1UbP15BHknWLLXRZkeFK+GD+QZ7vZCWdCkjv29Yz3n5dTFRp5UhguuS6W0FY/8R
      E0okMYItqUUI5HdZK+2QsdOOk+RyU+gG0+2sLQV3FS4g7BMz5eUR4UBB3trU9x6b
      3RRMk1JALaQKR59kFLGtQeNpz5LGfJufgfCvRptdNo3S/mQZ
      -----END CERTIFICATE-----