apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: lagoobernetes-openshift-template-kibana
parameters:
  - name: SERVICE_NAME
    description: Name of this service
    required: true
  - name: SAFE_BRANCH
    description: Which branch this belongs to, special chars replaced with dashes
    required: true
  - name: SAFE_PROJECT
    description: Which project this belongs to, special chars replaced with dashes
    required: true
  - name: BRANCH
    description: Which branch this belongs to, original value
    required: true
  - name: PROJECT
    description: Which project this belongs to, original value
    required: true
  - name: LAGOOBERNETES_GIT_SHA
    description: git hash sha of the current deployment
    required: true
  - name: SERVICE_ROUTER_URL
    description: URL of the Router for this service
    value: ""
  - name: OPENSHIFT_PROJECT
    description: Name of the Project that this service is in
    required: true
  - name: REGISTRY
    description: Registry where Images are pushed to
    required: true
  - name: DEPLOYMENT_STRATEGY
    description: Strategy of Deploymentconfig
    value: "Rolling"
  - name: SERVICE_IMAGE
    description: Pullable image of service
    required: true
  - name: CRONJOBS
    description: Oneliner of Cronjobs
    value: ""
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      service: ${SERVICE_NAME}
      branch: ${SAFE_BRANCH}
      project: ${SAFE_PROJECT}
    name: ${SERVICE_NAME}
  spec:
    replicas: 2
    selector:
      service: ${SERVICE_NAME}
    strategy:
      type: ${DEPLOYMENT_STRATEGY}
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: ${SERVICE_NAME}
          branch: ${SAFE_BRANCH}
          project: ${SAFE_PROJECT}
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: service
                      operator: In
                      values:
                        - ${SERVICE_NAME}
                topologyKey: kubernetes.io/hostname
        containers:
        - image: ${SERVICE_IMAGE}
          name: ${SERVICE_NAME}
          ports:
          - containerPort: 5601
            protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 5601
            initialDelaySeconds: 20
          livenessProbe:
            tcpSocket:
              port: 5601
            initialDelaySeconds: 120
          envFrom:
          - configMapRef:
              name: lagoobernetes-env
          env:
          - name: SERVICE_NAME
            value: ${SERVICE_NAME}
          - name: CRONJOBS
            value: ${CRONJOBS}
          - name: LOGSDB_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: LOGSDB_ADMIN_PASSWORD
                name: logs-db-admin-password
          - name: LOGSDB_KIBANASERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                key: LOGSDB_KIBANASERVER_PASSWORD
                name: logs-db-kibanaserver-password
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-admin-password
                key: KEYCLOAK_ADMIN_PASSWORD
          - name: OPENDISTRO_SECURITY_COOKIE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: opendistro-security-cookie-password
                key: OPENDISTRO_SECURITY_COOKIE_PASSWORD
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
    test: false
    triggers:
    - type: ConfigChange
  status: {}
