apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: lagoobernetes-openshift-template-dbaas-crd
parameters:
  - name: SERVICE_NAME
    description: Name of this service
    required: true
  - name: SAFE_BRANCH
    description: Which branch this belongs to, special chars replaced with dashes
    required: true
  - name: SAFE_PROJECT
    description: Which project this belongs to, special chars replaced with dashes
    required: true
  - name: ENVIRONMENT
    description: Environment or type of dbaas to choose
    required: true
objects:
- apiVersion: mariadb.amazee.io/v1
  kind: MariaDBConsumer
  metadata:
    name: ${SERVICE_NAME}
    labels:
      service: ${SERVICE_NAME}
      branch: ${SAFE_BRANCH}
      project: ${SAFE_PROJECT}
  spec:
    environment: ${ENVIRONMENT}